Repository fe-bootcamp-2021/chat-app, pull requests merged in 2021-08, with the labels that each got.

#1 Dev
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/favicon.svg
  src/helpers/idGenerator.js
  src/img/icons.jsx
  src/logo.svg
  src/services/country.js
Labels: enhancement

#10 feat(index): Added seo meta tags
  index.html
  src/img/seo/celegram.png
  src/img/seo/telegram.jpg
Labels: enhancement

#23 fix(*): folder structure for auth
  src/App.jsx
  src/components/Auth/Auth.css
  src/components/Auth/Auth.jsx
  src/components/Login/Login.css
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
Labels: fixed

#24 fix(*): inline styles delted
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
Labels: fixed

#25 delete(services): dont need service yet
  src/services/country.js
Labels: Delete

#26 fix(*): icons.jsx replaced
  src/components/Icons/icons.jsx
Labels: fixed

#27 feat(package*): classname installed
  package-lock.json
  package.json
Labels: fixed

#28 Future/validate
  index.html
  src/App.css
  src/components/Auth/Auth.css
  src/components/Auth/Auth.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.module.css
  src/components/Login/Login.jsx
  src/components/Login/Login.module.css
  src/components/Register/Register.jsx
  src/components/Register/Register.module.css
  src/index.css
  src/root.css
Labels: enhancement

#29 feat(*): firebase install
  package-lock.json
  package.json
Labels: enhancement

#31 fix(firebase.js): name's fixed
  src/firebase.js
Labels: fixed

#32 Feat/firebase
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
  src/firebase.js
  src/services/signInWithEmailAndPassword.js
  src/services/signUpWithEmailAndPassword.js
Labels: enhancement, fixed, Delete

#33 fix(*): input label positioning fixed
  src/components/Input/Input.module.css
Labels: fixed

#37 fix(src): Change the validation error and the ability to repeat the password...
  src/components/Input/Input.module.css
  src/components/Login/Login.jsx
  src/components/Login/Login.module.css
  src/components/Register/Register.jsx
  src/components/Register/Register.module.css
Labels: bug, enhancement, fixed

#38 feat(services/signin): invalid alert
  src/services/signInWithEmailAndPassword.js
Labels: fixed

#39 feat(Button): Added Button component
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Login/Login.jsx
  src/components/Login/Login.module.css
  src/components/Register/Register.jsx
  src/components/Register/Register.module.css
Labels: enhancement

#40 feat(src): Added propTypes
  src/components/Button/Button.jsx
  src/components/Input/Input.jsx
Labels: enhancement

#41 Fix open string
  src/components/Auth/Auth.jsx
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
  src/constants/routes.js
  src/constants/types.js
Labels: fixed

#43 fix(*): button prop types and label fixed
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
  src/constants/types.js
Labels: fixed

#46 Feature/new chat menu
  src/components/Auth/Auth.jsx
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Icons/icons.jsx
  src/components/Login/Login.jsx
  src/components/Login/Login.module.css
  src/components/NewChatMenu/NewChatMenu.jsx
  src/components/NewChatMenu/NewChatMenu.module.css
  src/components/Register/Register.jsx
  src/components/Register/Register.module.css
  src/root.css
Labels: enhancement

#47 Feature/to chat menu
  src/components/Login/Login.jsx
  src/components/NewChatMenu/NewChatMenu.jsx
  src/components/NewChatMenu/NewChatMenu.module.css
  src/components/Search/Search.module.css
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/components/ToChatMenu/ToChatMenu.jsx
  src/components/ToChatMenu/ToChatMenu.module.css
  src/constants/types.js
  src/root.css
Labels: enhancement

#48 fix(newChatMenu): style fixed
  src/components/NewChatMenu/NewChatMenu.module.css
Labels: fixed

#50 feat(colorGenerator): generator created
  src/helpers/colorGenerator.js
Labels: enhancement

#51 Fix
  src/components/BurgerMenu/BurgerMenu.module.css
  src/components/NewChatMenu/NewChatMenu.module.css
  src/components/Search/Search.module.css
  src/components/Sidebar/Sidebar.module.css
  src/components/ToChatMenu/ToChatMenu.jsx
  src/components/ToChatMenu/ToChatMenu.module.css
Labels: fixed

#52 fix(sidebar): html construction for menu
  src/components/Sidebar/Sidebar.jsx
  src/root.css
Labels: fixed

#54 Feat
  src/components/AppleCheckbox/AppleCheckbox.css
  src/components/BurgerMenu/BurgerMenu.jsx
  src/components/BurgerMenu/BurgerMenu.module.css
  src/components/Icons/icons.jsx
  src/components/NewChatMenuRow/NewChatMenuRow.jsx
Labels: enhancement

#55 Feature/chat
  src/components/Chat/Chat.jsx
  src/components/Chat/Chat.module.css
  src/components/DotMenu/DotMenu.jsx
  src/components/DotMenu/DotMenu.module.css
  src/components/Icons/icons.jsx
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
  src/components/Message/Message.jsx
  src/components/Message/Message.module.css
  src/components/NavBarChat/NavBarChat.jsx
  src/components/NavBarChat/NavBarChat.module.css
  src/components/NewChatMenu/NewChatMenu.jsx
  src/components/NewChatMenu/NewChatMenu.module.css
  src/components/NewChatMenuRow/NewChatMenuRow.jsx
  src/components/NewChatMenuRow/NewChatMenuRow.module.css
  src/components/Sidebar/Sidebar.jsx
  src/components/ToChatMenu/ToChatMenu.module.css
  src/index.css
  src/root.css
Labels: bug, enhancement, fixed

#58 DotMenu && NavBarChat
  src/components/DotMenu/DotMenu.jsx
  src/components/DotMenu/DotMenu.module.css
  src/components/NavBarChat/NavBarChat.jsx
  src/components/NavBarChat/NavBarChat.module.css
Labels: fixed

#71 fix(src): Change files name
  src/components/Auth/Auth.jsx
  src/components/BurgerMenu/BurgerMenu.jsx
  src/components/Button/Button.jsx
  src/components/DotMenu/DotMenu.jsx
  src/components/Input/Input.jsx
  src/components/Login/Login.jsx
  src/components/NavBarChat/NavBarChat.jsx
  src/components/NavBarChat/NavBarChat.module.css
  src/components/NewChatMenu/NewChatMenu.jsx
  src/components/NewChatMenuRow/NewChatMenuRow.jsx
  src/components/Register/Register.jsx
  src/components/Search/Search.jsx
  src/components/ToChatMenu/ToChatMenu.jsx
  src/constants/formTypes.constant.js
  src/constants/routes.constant.js
  src/helpers/colorGenerator.helper.js
  src/helpers/formValidation.helper.js
  src/helpers/idGenerator.helper.js
  src/index.css
  src/services/signInWithEmailAndPassword.services.js
  src/services/signUpWithEmailAndPassword.services.js
Labels: bug, fixed

#72 fix(*): styles
  src/components/NavBarChat/NavBarChat.jsx
  src/components/NavBarChat/NavBarChat.module.css
Labels: fixed

#73 fix(*): now firebase working with checking pass and mail
  src/components/Button/Button.jsx
  src/components/Login/Login.jsx
  src/services/signInWithEmailAndPassword.services.js
Labels: fixed

#76 New Features
  src/components/Chat/Chat.jsx
  src/components/FileUpload/FileUpload.jsx
  src/components/FileUpload/FileUpload.module.css
  src/components/Icons/icons.jsx
  src/components/MessageInput/MessageInput.jsx
  src/components/MessageInput/MessageInput.module.css
  src/components/SendMessage/SendMessage.jsx
  src/components/SendMessage/SendMessage.module.css
  src/constants/formTypes.constant.js
Labels: enhancement, Delete

#80 Feat
  src/components/Chat/Chat.jsx
  src/components/Message/Message.jsx
  src/components/Message/Message.module.css
  src/components/MessageInput/MessageInput.jsx
  src/components/MessageInput/MessageInput.module.css
  src/constants/formTypes.constant.js
  src/constants/messageTypes.constant.js
Labels: enhancement, fixed

#81 fix(src): import order
  src/App.jsx
  src/components/AppleCheckbox/AppleCheckbox.jsx
  src/components/Auth/Auth.jsx
  src/components/BurgerMenu/BurgerMenu.jsx
  src/components/Chat/Chat.jsx
  src/components/DotMenu/DotMenu.jsx
  src/components/FileUpload/FileUpload.jsx
  src/components/Input/Input.jsx
  src/components/Login/Login.jsx
  src/components/Main/Main.jsx
  src/components/Message/Message.jsx
  src/components/MessageInput/MessageInput.jsx
  src/components/NavBarChat/NavBarChat.jsx
  src/components/NewChatMenu/NewChatMenu.jsx
  src/components/NewChatMenuRow/NewChatMenuRow.jsx
  src/components/Register/Register.jsx
  src/components/Search/Search.jsx
  src/components/SendMessage/SendMessage.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/ToChatMenu/ToChatMenu.jsx
Labels: bug, fixed

#83 feat(src): Added AuthenticatedApp and UnAuthenticatedApp components
  src/App.jsx
  src/components/AuthenticatedApp/AuthenticatedApp.jsx
  src/components/BurgerMenu/BurgerMenu.jsx
  src/components/DotMenu/DotMenu.jsx
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
  src/components/UnAuthenticatedApp/UnAuthenticatedApp.jsx
  src/constants/routes.constant.js
  src/hooks/useAuth.hook.jsx
  src/main.jsx
  src/services/signInWithEmailAndPassword.services.js
  src/services/signUpWithEmailAndPassword.services.js
  src/services/user.services.js
  vite.config.js
Labels: enhancement
